### ISSUE TITLE
Serving frontend as a single page application isn't working for paths outside `/` and `index.html`

### ISSUE THREAD

**Issue by iburakov** [ryukzak/nitta#101]
### Reproducing steps
1. Open the web UI
2. Go to any non-index page (for example, `/subforest`)
3. Refresh the page in web browser
4. Observe the "File not found" error

### Expected outcome
Same web UI page is displayed after refreshing.

### How to fix
Modify the server-side HTTP request routing url patterns to comply with the following:
- If a static file is requested (e.g. `/css/style.css`) then serve it. 
- If not (e.g. `/node`) then serve the `index.html` file. As is. For any url, be it `/subforest`, `/givemecookies` or whatever. Do not use the HTTP redirect. Actual mapping of the URL to the page content and its displaying will be handled client-side (in browser using JavaScirpt & React Router). 

The easiest way to implement that would be to check if there's a file for corresponding url (`/css/style.css`). If there is, serve it. If not, serve the `index.html`.

For more insight on why this should work the way described, learn how the [routing in SPA works](https://dev.to/marcomonsanto/routing-in-spas-173i), but that shouldn't be needed.

**Comment by eugenemiko** [comment]
Hello. I would like to push my implementation for a review, but I don't have sufficient permissions.
Can someone provide them?
