### ISSUE TITLE
Reorganize microarchitecture builder to direct work with BusNetwork

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/nitta#154]
In module `NITTA.Model.Microarchitecture` we build BusNetwork by collecting data structure with all required information, and after that build BusNetwork object.

This approach is not applicable, if we want to modify BusNetwork (e.g. adding a new PU) during a synthesis process.

To do that, we need to reorganize our microarchitecture builder by adding the function to add PU to BusNetwork directly (`addUnit :: ...... -> BusNetwork ... -> BusNetwork ...`).

Of course, we need to save the external builder API.

**Comment by BasicEC** [comment]
@ryukzak, do we need to support removing PU from BusNetwork here?

**Comment by ryukzak** [comment]
> @ryukzak, do we need to support removing `PU` from `BusNetwork` here?

No
