### ISSUE TITLE
Show help message on blank run

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/nitta#175]
Currently:
```shell
$ stack exec nitta
Requires at least 1 arguments, got 0
```

Expected (output of `--help` message):
```shell
$ stack exec nitta
nitta v0.0.0.1 - CAD for reconfigurable real-time ASIP

nitta [OPTIONS] FILE

Common flags:
  -t     --type=ITEM                  Data type (default: 'fx32.32')
  -i     --io-sync=IOSYNCHRONIZATION  IO synchronization mode: sync, async,
                                      onboard
  -p     --port=INT                   Run nitta server for UI on specific
                                      port (by default - not run)
         --templates=ITEM             Specify target platform templates (':',
                                      default:
                                      'templates/Icarus:templates/DE0-Nano')
  -n=INT                              Number of computation cycles for
                                      simulation and testbench
         --fsim                       Functional simulation with trace
  -l     --lsim                       Logical (HDL) simulation with trace
  -v     --verbose                    Verbose
  -o     --output-path=ITEM           Place the output into specified
                                      directory
         --format=ITEM                Specify logical (HDL) or functional
                                      simulation output format: md, json, csv
                                      (default: 'md')
  -?     --help                       Display help message
  -V     --version                    Print version information
         --numeric-version            Print just the version number
```

**Comment by burzomir** [comment]
Hi, my proposed solution is to handle args parsing error and transform it into the second call for args, but with '--help' flag passed.

See the proposal:
https://github.com/ryukzak/nitta/compare/master...burzomir:175-display-help-if-no-args-provided?expand=1

**Comment by ryukzak** [comment]
> Hi, my proposed solution is to handle args parsing error and transform it into the second call for args, but with '--help' flag passed.
> 
> See the proposal:
> https://github.com/ryukzak/nitta/compare/master...burzomir:175-display-help-if-no-args-provided?expand=1

Looks good. Can you make a pull request and improve few things?
- import System.Console.CmdArgs.Explicit as Cmd
- print an error message before the help message to be more informative in case of none oblivious input error
- add to PR an output on bad args

**Comment by burzomir** [comment]
I created the PR: https://github.com/ryukzak/nitta/pull/176

Keeping the error message before help text resulted in simplification of the code and removal of `import System.Console.CmdArgs.Explicit as Cmd`.
