### ISSUE TITLE
Synthesis failes

### ISSUE THREAD

**Issue by BasicEC** [ryukzak/nitta#217]
Lua code:
```lua
function sum(x1, x2)
     x1 = x1 + x2
     x2 = x2 + 3
     sum(x1, x2)
end
sum(1,2,3)
```

DFG at the moment of stop:
![image](https://user-images.githubusercontent.com/31983783/168478910-9a312354-113f-4b42-bbc7-a93882fee289.png)

**Comment by BasicEC** [comment]
My **guess** is that the FRAM can't overwrite x2 variable because it is needed for second `add` function. So we have dead lock here.

Maybe related: #213

**Comment by ryukzak** [comment]
Not reproduce. But highlight the following problem https://github.com/ryukzak/nitta/issues/267
