### ISSUE TITLE
Implement external synthesis by ML (via Python script and NITTA REST API)

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/nitta#233]
Currently, in https://github.com/ryukzak/nitta/pull/167 we have a data crawler to collect data from the synthesis tree, but it can't control the synthesis process by the educated model. So, we need to implement such a script for the following workflow:

1. Run NITTA with web UI.
2. Run ml-synthesis script.
3. See the result in UI.

**Comment by iburakov** [comment]
The ML synthesis was recently integrated into Haskell control flow (#167). Is this problem solved?
