### ISSUE TITLE
UI: Refactor IntermediateView

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/nitta#94]
Currently, `IntermediateView.tsx` is too complicated. It should be rewritten like `MicroarchitectureView.tsx`.

The number of rendering and renderGraphJsonToDot calls should be minimized (see https://github.com/ryukzak/nitta/issues/100).

**Comment by burzomir** [comment]
I did some work related to this issue. It also covers solution proposal for https://github.com/ryukzak/nitta/issues/94. See `useResponseApi.ts`.  https://github.com/ryukzak/nitta/compare/master...burzomir:94-refactor-intermediate-view?expand=1

**Comment by ryukzak** [comment]
Thank you, I create the PR https://github.com/ryukzak/nitta/pull/180 for this and require a review from @iburako (he know much bigger about this technology than me).  

From my point of view it looks acceptable.
